version: '3.8'
services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: